apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dcgm-exporter-daemonset
spec:
  template:
    metadata:
      labels:
        name: dcgm-exporter-ds
    spec:
      containers:
      - image: nvidia/dcgm-exporter:1.4.3
        name: dcgm-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - name: collector-textfiles
            mountPath: /run/prometheus
      volumes:
        - name: collector-textfiles
          emptyDir:
            medium: Memory
